/**
 *
 *  StaffMember.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace LeaveBooking
{
class StaffMember;

class StaffMember
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _first_name;
        static const std::string _surname;
        static const std::string _house_name_number;
        static const std::string _street;
        static const std::string _town;
        static const std::string _postcode;
        static const std::string _role;
        static const std::string _employment_status;
        static const std::string _manager_id;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit StaffMember(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit StaffMember(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    StaffMember(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    StaffMember() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column first_name  */
    ///Get the value of the column first_name, returns the default value if the column is null
    const std::string &getValueOfFirstName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFirstName() const noexcept;
    ///Set the value of the column first_name
    void setFirstName(const std::string &pFirstName) noexcept;
    void setFirstName(std::string &&pFirstName) noexcept;

    /**  For column surname  */
    ///Get the value of the column surname, returns the default value if the column is null
    const std::string &getValueOfSurname() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSurname() const noexcept;
    ///Set the value of the column surname
    void setSurname(const std::string &pSurname) noexcept;
    void setSurname(std::string &&pSurname) noexcept;

    /**  For column house_name_number  */
    ///Get the value of the column house_name_number, returns the default value if the column is null
    const std::string &getValueOfHouseNameNumber() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getHouseNameNumber() const noexcept;
    ///Set the value of the column house_name_number
    void setHouseNameNumber(const std::string &pHouseNameNumber) noexcept;
    void setHouseNameNumber(std::string &&pHouseNameNumber) noexcept;
    void setHouseNameNumberToNull() noexcept;

    /**  For column street  */
    ///Get the value of the column street, returns the default value if the column is null
    const std::string &getValueOfStreet() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStreet() const noexcept;
    ///Set the value of the column street
    void setStreet(const std::string &pStreet) noexcept;
    void setStreet(std::string &&pStreet) noexcept;
    void setStreetToNull() noexcept;

    /**  For column town  */
    ///Get the value of the column town, returns the default value if the column is null
    const std::string &getValueOfTown() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTown() const noexcept;
    ///Set the value of the column town
    void setTown(const std::string &pTown) noexcept;
    void setTown(std::string &&pTown) noexcept;
    void setTownToNull() noexcept;

    /**  For column postcode  */
    ///Get the value of the column postcode, returns the default value if the column is null
    const std::string &getValueOfPostcode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPostcode() const noexcept;
    ///Set the value of the column postcode
    void setPostcode(const std::string &pPostcode) noexcept;
    void setPostcode(std::string &&pPostcode) noexcept;
    void setPostcodeToNull() noexcept;

    /**  For column role  */
    ///Get the value of the column role, returns the default value if the column is null
    const std::string &getValueOfRole() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRole() const noexcept;
    ///Set the value of the column role
    void setRole(const std::string &pRole) noexcept;
    void setRole(std::string &&pRole) noexcept;

    /**  For column employment_status  */
    ///Get the value of the column employment_status, returns the default value if the column is null
    const std::string &getValueOfEmploymentStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEmploymentStatus() const noexcept;
    ///Set the value of the column employment_status
    void setEmploymentStatus(const std::string &pEmploymentStatus) noexcept;
    void setEmploymentStatus(std::string &&pEmploymentStatus) noexcept;

    /**  For column manager_id  */
    ///Get the value of the column manager_id, returns the default value if the column is null
    const std::string &getValueOfManagerId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getManagerId() const noexcept;
    ///Set the value of the column manager_id
    void setManagerId(const std::string &pManagerId) noexcept;
    void setManagerId(std::string &&pManagerId) noexcept;
    void setManagerIdToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 10;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    StaffMember getStaffMember(const drogon::orm::DbClientPtr &clientPtr) const;
    void getStaffMember(const drogon::orm::DbClientPtr &clientPtr,
                        const std::function<void(StaffMember)> &rcb,
                        const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<StaffMember>;
    friend drogon::orm::BaseBuilder<StaffMember, true, true>;
    friend drogon::orm::BaseBuilder<StaffMember, true, false>;
    friend drogon::orm::BaseBuilder<StaffMember, false, true>;
    friend drogon::orm::BaseBuilder<StaffMember, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<StaffMember>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> firstName_;
    std::shared_ptr<std::string> surname_;
    std::shared_ptr<std::string> houseNameNumber_;
    std::shared_ptr<std::string> street_;
    std::shared_ptr<std::string> town_;
    std::shared_ptr<std::string> postcode_;
    std::shared_ptr<std::string> role_;
    std::shared_ptr<std::string> employmentStatus_;
    std::shared_ptr<std::string> managerId_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[10]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "id,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "first_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "surname,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "house_name_number,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "street,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "town,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "postcode,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "role,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "employment_status,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "manager_id,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace LeaveBooking
} // namespace drogon_model
