/**
 *
 *  LeaveController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "infrastructure/server/api/LeaveController.hpp"
#include <string>
/*
void LeaveController::update(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{

}
*/



