/**
 *
 *  LeaveController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "infrastructure/server/api/StaffController.hpp"
#include <string>
/*
void StaffController::update(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{

}
*/

void StaffController::getStaffMember(
	    const HttpRequestPtr& req,
	    std::function<void (const HttpResponsePtr&)>&& callback,
	    std::string staffId
	    ){

}

