/**
 *
 *  LeaveRequest.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "infrastructure/persistence/models/LeaveRequest.hpp"
#include "infrastructure/persistence/models/StaffMember.hpp"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::LeaveBooking;

const std::string LeaveRequest::Cols::_id = "\"id\"";
const std::string LeaveRequest::Cols::_staff_id = "\"staff_id\"";
const std::string LeaveRequest::Cols::_start_date = "\"start_date\"";
const std::string LeaveRequest::Cols::_end_date = "\"end_date\"";
const std::string LeaveRequest::Cols::_leave_reason = "\"leave_reason\"";
const std::string LeaveRequest::Cols::_leave_status = "\"leave_status\"";
const std::string LeaveRequest::primaryKeyName = "id";
const bool LeaveRequest::hasPrimaryKey = true;
const std::string LeaveRequest::tableName = "\"leave_request\"";

const std::vector<typename LeaveRequest::MetaData> LeaveRequest::metaData_={
{"id","std::string","text",0,0,1,1},
{"staff_id","std::string","text",0,0,0,1},
{"start_date","::trantor::Date","date",0,0,0,1},
{"end_date","::trantor::Date","date",0,0,0,1},
{"leave_reason","std::string","text",0,0,0,1},
{"leave_status","std::string","text",0,0,0,1}
};
const std::string &LeaveRequest::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
LeaveRequest::LeaveRequest(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["staff_id"].isNull())
        {
            staffId_=std::make_shared<std::string>(r["staff_id"].as<std::string>());
        }
        if(!r["start_date"].isNull())
        {
            auto daysStr = r["start_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            stm.tm_isdst = -1;
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["end_date"].isNull())
        {
            auto daysStr = r["end_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            stm.tm_isdst = -1;
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            endDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["leave_reason"].isNull())
        {
            leaveReason_=std::make_shared<std::string>(r["leave_reason"].as<std::string>());
        }
        if(!r["leave_status"].isNull())
        {
            leaveStatus_=std::make_shared<std::string>(r["leave_status"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            staffId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            stm.tm_isdst = -1;
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            stm.tm_isdst = -1;
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            endDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            leaveReason_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            leaveStatus_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

LeaveRequest::LeaveRequest(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            staffId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            stm.tm_isdst = -1;
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            stm.tm_isdst = -1;
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            endDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            leaveReason_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            leaveStatus_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

LeaveRequest::LeaveRequest(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("staff_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["staff_id"].isNull())
        {
            staffId_=std::make_shared<std::string>(pJson["staff_id"].asString());
        }
    }
    if(pJson.isMember("start_date"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["start_date"].isNull())
        {
            auto daysStr = pJson["start_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            stm.tm_isdst = -1;
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("end_date"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["end_date"].isNull())
        {
            auto daysStr = pJson["end_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            stm.tm_isdst = -1;
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            endDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("leave_reason"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["leave_reason"].isNull())
        {
            leaveReason_=std::make_shared<std::string>(pJson["leave_reason"].asString());
        }
    }
    if(pJson.isMember("leave_status"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["leave_status"].isNull())
        {
            leaveStatus_=std::make_shared<std::string>(pJson["leave_status"].asString());
        }
    }
}

void LeaveRequest::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            staffId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            stm.tm_isdst = -1;
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            stm.tm_isdst = -1;
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            endDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            leaveReason_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            leaveStatus_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

void LeaveRequest::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("staff_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["staff_id"].isNull())
        {
            staffId_=std::make_shared<std::string>(pJson["staff_id"].asString());
        }
    }
    if(pJson.isMember("start_date"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["start_date"].isNull())
        {
            auto daysStr = pJson["start_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            stm.tm_isdst = -1;
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("end_date"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["end_date"].isNull())
        {
            auto daysStr = pJson["end_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            stm.tm_isdst = -1;
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            endDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("leave_reason"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["leave_reason"].isNull())
        {
            leaveReason_=std::make_shared<std::string>(pJson["leave_reason"].asString());
        }
    }
    if(pJson.isMember("leave_status"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["leave_status"].isNull())
        {
            leaveStatus_=std::make_shared<std::string>(pJson["leave_status"].asString());
        }
    }
}

const std::string &LeaveRequest::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &LeaveRequest::getId() const noexcept
{
    return id_;
}
void LeaveRequest::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void LeaveRequest::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename LeaveRequest::PrimaryKeyType & LeaveRequest::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &LeaveRequest::getValueOfStaffId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(staffId_)
        return *staffId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &LeaveRequest::getStaffId() const noexcept
{
    return staffId_;
}
void LeaveRequest::setStaffId(const std::string &pStaffId) noexcept
{
    staffId_ = std::make_shared<std::string>(pStaffId);
    dirtyFlag_[1] = true;
}
void LeaveRequest::setStaffId(std::string &&pStaffId) noexcept
{
    staffId_ = std::make_shared<std::string>(std::move(pStaffId));
    dirtyFlag_[1] = true;
}

const ::trantor::Date &LeaveRequest::getValueOfStartDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(startDate_)
        return *startDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &LeaveRequest::getStartDate() const noexcept
{
    return startDate_;
}
void LeaveRequest::setStartDate(const ::trantor::Date &pStartDate) noexcept
{
    startDate_ = std::make_shared<::trantor::Date>(pStartDate.roundDay());
    dirtyFlag_[2] = true;
}

const ::trantor::Date &LeaveRequest::getValueOfEndDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(endDate_)
        return *endDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &LeaveRequest::getEndDate() const noexcept
{
    return endDate_;
}
void LeaveRequest::setEndDate(const ::trantor::Date &pEndDate) noexcept
{
    endDate_ = std::make_shared<::trantor::Date>(pEndDate.roundDay());
    dirtyFlag_[3] = true;
}

const std::string &LeaveRequest::getValueOfLeaveReason() const noexcept
{
    static const std::string defaultValue = std::string();
    if(leaveReason_)
        return *leaveReason_;
    return defaultValue;
}
const std::shared_ptr<std::string> &LeaveRequest::getLeaveReason() const noexcept
{
    return leaveReason_;
}
void LeaveRequest::setLeaveReason(const std::string &pLeaveReason) noexcept
{
    leaveReason_ = std::make_shared<std::string>(pLeaveReason);
    dirtyFlag_[4] = true;
}
void LeaveRequest::setLeaveReason(std::string &&pLeaveReason) noexcept
{
    leaveReason_ = std::make_shared<std::string>(std::move(pLeaveReason));
    dirtyFlag_[4] = true;
}

const std::string &LeaveRequest::getValueOfLeaveStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(leaveStatus_)
        return *leaveStatus_;
    return defaultValue;
}
const std::shared_ptr<std::string> &LeaveRequest::getLeaveStatus() const noexcept
{
    return leaveStatus_;
}
void LeaveRequest::setLeaveStatus(const std::string &pLeaveStatus) noexcept
{
    leaveStatus_ = std::make_shared<std::string>(pLeaveStatus);
    dirtyFlag_[5] = true;
}
void LeaveRequest::setLeaveStatus(std::string &&pLeaveStatus) noexcept
{
    leaveStatus_ = std::make_shared<std::string>(std::move(pLeaveStatus));
    dirtyFlag_[5] = true;
}

void LeaveRequest::updateId(const uint64_t id)
{
}

const std::vector<std::string> &LeaveRequest::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "staff_id",
        "start_date",
        "end_date",
        "leave_reason",
        "leave_status"
    };
    return inCols;
}

void LeaveRequest::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getStaffId())
        {
            binder << getValueOfStaffId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getStartDate())
        {
            binder << getValueOfStartDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getEndDate())
        {
            binder << getValueOfEndDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getLeaveReason())
        {
            binder << getValueOfLeaveReason();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLeaveStatus())
        {
            binder << getValueOfLeaveStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> LeaveRequest::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void LeaveRequest::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getStaffId())
        {
            binder << getValueOfStaffId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getStartDate())
        {
            binder << getValueOfStartDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getEndDate())
        {
            binder << getValueOfEndDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getLeaveReason())
        {
            binder << getValueOfLeaveReason();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLeaveStatus())
        {
            binder << getValueOfLeaveStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value LeaveRequest::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getStaffId())
    {
        ret["staff_id"]=getValueOfStaffId();
    }
    else
    {
        ret["staff_id"]=Json::Value();
    }
    if(getStartDate())
    {
        ret["start_date"]=getStartDate()->toDbStringLocal();
    }
    else
    {
        ret["start_date"]=Json::Value();
    }
    if(getEndDate())
    {
        ret["end_date"]=getEndDate()->toDbStringLocal();
    }
    else
    {
        ret["end_date"]=Json::Value();
    }
    if(getLeaveReason())
    {
        ret["leave_reason"]=getValueOfLeaveReason();
    }
    else
    {
        ret["leave_reason"]=Json::Value();
    }
    if(getLeaveStatus())
    {
        ret["leave_status"]=getValueOfLeaveStatus();
    }
    else
    {
        ret["leave_status"]=Json::Value();
    }
    return ret;
}

std::string LeaveRequest::toString() const
{
    return toJson().toStyledString();
}

Json::Value LeaveRequest::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getStaffId())
            {
                ret[pMasqueradingVector[1]]=getValueOfStaffId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getStartDate())
            {
                ret[pMasqueradingVector[2]]=getStartDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getEndDate())
            {
                ret[pMasqueradingVector[3]]=getEndDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getLeaveReason())
            {
                ret[pMasqueradingVector[4]]=getValueOfLeaveReason();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getLeaveStatus())
            {
                ret[pMasqueradingVector[5]]=getValueOfLeaveStatus();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getStaffId())
    {
        ret["staff_id"]=getValueOfStaffId();
    }
    else
    {
        ret["staff_id"]=Json::Value();
    }
    if(getStartDate())
    {
        ret["start_date"]=getStartDate()->toDbStringLocal();
    }
    else
    {
        ret["start_date"]=Json::Value();
    }
    if(getEndDate())
    {
        ret["end_date"]=getEndDate()->toDbStringLocal();
    }
    else
    {
        ret["end_date"]=Json::Value();
    }
    if(getLeaveReason())
    {
        ret["leave_reason"]=getValueOfLeaveReason();
    }
    else
    {
        ret["leave_reason"]=Json::Value();
    }
    if(getLeaveStatus())
    {
        ret["leave_status"]=getValueOfLeaveStatus();
    }
    else
    {
        ret["leave_status"]=Json::Value();
    }
    return ret;
}

bool LeaveRequest::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    else
    {
        err="The id column cannot be null";
        return false;
    }
    if(pJson.isMember("staff_id"))
    {
        if(!validJsonOfField(1, "staff_id", pJson["staff_id"], err, true))
            return false;
    }
    else
    {
        err="The staff_id column cannot be null";
        return false;
    }
    if(pJson.isMember("start_date"))
    {
        if(!validJsonOfField(2, "start_date", pJson["start_date"], err, true))
            return false;
    }
    else
    {
        err="The start_date column cannot be null";
        return false;
    }
    if(pJson.isMember("end_date"))
    {
        if(!validJsonOfField(3, "end_date", pJson["end_date"], err, true))
            return false;
    }
    else
    {
        err="The end_date column cannot be null";
        return false;
    }
    if(pJson.isMember("leave_reason"))
    {
        if(!validJsonOfField(4, "leave_reason", pJson["leave_reason"], err, true))
            return false;
    }
    else
    {
        err="The leave_reason column cannot be null";
        return false;
    }
    if(pJson.isMember("leave_status"))
    {
        if(!validJsonOfField(5, "leave_status", pJson["leave_status"], err, true))
            return false;
    }
    else
    {
        err="The leave_status column cannot be null";
        return false;
    }
    return true;
}
bool LeaveRequest::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool LeaveRequest::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("staff_id"))
    {
        if(!validJsonOfField(1, "staff_id", pJson["staff_id"], err, false))
            return false;
    }
    if(pJson.isMember("start_date"))
    {
        if(!validJsonOfField(2, "start_date", pJson["start_date"], err, false))
            return false;
    }
    if(pJson.isMember("end_date"))
    {
        if(!validJsonOfField(3, "end_date", pJson["end_date"], err, false))
            return false;
    }
    if(pJson.isMember("leave_reason"))
    {
        if(!validJsonOfField(4, "leave_reason", pJson["leave_reason"], err, false))
            return false;
    }
    if(pJson.isMember("leave_status"))
    {
        if(!validJsonOfField(5, "leave_status", pJson["leave_status"], err, false))
            return false;
    }
    return true;
}
bool LeaveRequest::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool LeaveRequest::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
StaffMember LeaveRequest::getStaffMember(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from staff_member where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *staffId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return StaffMember(r[0]);
}

void LeaveRequest::getStaffMember(const DbClientPtr &clientPtr,
                                  const std::function<void(StaffMember)> &rcb,
                                  const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from staff_member where id = $1";
    *clientPtr << sql
               << *staffId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(StaffMember(r[0]));
                    }
               }
               >> ecb;
}
