/**
 *
 *  LeaveAllowance.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "infrastructure/persistence/models/LeaveAllowance.hpp"
#include "infrastructure/persistence/models/StaffMember.hpp"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::LeaveBooking;

const std::string LeaveAllowance::Cols::_id = "\"id\"";
const std::string LeaveAllowance::Cols::_staff_id = "\"staff_id\"";
const std::string LeaveAllowance::Cols::_annual_entitlement = "\"annual_entitlement\"";
const std::string LeaveAllowance::Cols::_remaining_leave = "\"remaining_leave\"";
const std::string LeaveAllowance::primaryKeyName = "id";
const bool LeaveAllowance::hasPrimaryKey = true;
const std::string LeaveAllowance::tableName = "\"leave_allowance\"";

const std::vector<typename LeaveAllowance::MetaData> LeaveAllowance::metaData_={
{"id","std::string","text",0,0,1,1},
{"staff_id","std::string","text",0,0,0,1},
{"annual_entitlement","int32_t","integer",4,0,0,1},
{"remaining_leave","int32_t","integer",4,0,0,1}
};
const std::string &LeaveAllowance::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
LeaveAllowance::LeaveAllowance(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["staff_id"].isNull())
        {
            staffId_=std::make_shared<std::string>(r["staff_id"].as<std::string>());
        }
        if(!r["annual_entitlement"].isNull())
        {
            annualEntitlement_=std::make_shared<int32_t>(r["annual_entitlement"].as<int32_t>());
        }
        if(!r["remaining_leave"].isNull())
        {
            remainingLeave_=std::make_shared<int32_t>(r["remaining_leave"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            staffId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            annualEntitlement_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            remainingLeave_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

LeaveAllowance::LeaveAllowance(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            staffId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            annualEntitlement_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            remainingLeave_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
}

LeaveAllowance::LeaveAllowance(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("staff_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["staff_id"].isNull())
        {
            staffId_=std::make_shared<std::string>(pJson["staff_id"].asString());
        }
    }
    if(pJson.isMember("annual_entitlement"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["annual_entitlement"].isNull())
        {
            annualEntitlement_=std::make_shared<int32_t>((int32_t)pJson["annual_entitlement"].asInt64());
        }
    }
    if(pJson.isMember("remaining_leave"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["remaining_leave"].isNull())
        {
            remainingLeave_=std::make_shared<int32_t>((int32_t)pJson["remaining_leave"].asInt64());
        }
    }
}

void LeaveAllowance::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            staffId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            annualEntitlement_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            remainingLeave_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
}

void LeaveAllowance::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("staff_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["staff_id"].isNull())
        {
            staffId_=std::make_shared<std::string>(pJson["staff_id"].asString());
        }
    }
    if(pJson.isMember("annual_entitlement"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["annual_entitlement"].isNull())
        {
            annualEntitlement_=std::make_shared<int32_t>((int32_t)pJson["annual_entitlement"].asInt64());
        }
    }
    if(pJson.isMember("remaining_leave"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["remaining_leave"].isNull())
        {
            remainingLeave_=std::make_shared<int32_t>((int32_t)pJson["remaining_leave"].asInt64());
        }
    }
}

const std::string &LeaveAllowance::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &LeaveAllowance::getId() const noexcept
{
    return id_;
}
void LeaveAllowance::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void LeaveAllowance::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename LeaveAllowance::PrimaryKeyType & LeaveAllowance::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &LeaveAllowance::getValueOfStaffId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(staffId_)
        return *staffId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &LeaveAllowance::getStaffId() const noexcept
{
    return staffId_;
}
void LeaveAllowance::setStaffId(const std::string &pStaffId) noexcept
{
    staffId_ = std::make_shared<std::string>(pStaffId);
    dirtyFlag_[1] = true;
}
void LeaveAllowance::setStaffId(std::string &&pStaffId) noexcept
{
    staffId_ = std::make_shared<std::string>(std::move(pStaffId));
    dirtyFlag_[1] = true;
}

const int32_t &LeaveAllowance::getValueOfAnnualEntitlement() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(annualEntitlement_)
        return *annualEntitlement_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &LeaveAllowance::getAnnualEntitlement() const noexcept
{
    return annualEntitlement_;
}
void LeaveAllowance::setAnnualEntitlement(const int32_t &pAnnualEntitlement) noexcept
{
    annualEntitlement_ = std::make_shared<int32_t>(pAnnualEntitlement);
    dirtyFlag_[2] = true;
}

const int32_t &LeaveAllowance::getValueOfRemainingLeave() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(remainingLeave_)
        return *remainingLeave_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &LeaveAllowance::getRemainingLeave() const noexcept
{
    return remainingLeave_;
}
void LeaveAllowance::setRemainingLeave(const int32_t &pRemainingLeave) noexcept
{
    remainingLeave_ = std::make_shared<int32_t>(pRemainingLeave);
    dirtyFlag_[3] = true;
}

void LeaveAllowance::updateId(const uint64_t id)
{
}

const std::vector<std::string> &LeaveAllowance::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "staff_id",
        "annual_entitlement",
        "remaining_leave"
    };
    return inCols;
}

void LeaveAllowance::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getStaffId())
        {
            binder << getValueOfStaffId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAnnualEntitlement())
        {
            binder << getValueOfAnnualEntitlement();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRemainingLeave())
        {
            binder << getValueOfRemainingLeave();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> LeaveAllowance::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void LeaveAllowance::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getStaffId())
        {
            binder << getValueOfStaffId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAnnualEntitlement())
        {
            binder << getValueOfAnnualEntitlement();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRemainingLeave())
        {
            binder << getValueOfRemainingLeave();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value LeaveAllowance::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getStaffId())
    {
        ret["staff_id"]=getValueOfStaffId();
    }
    else
    {
        ret["staff_id"]=Json::Value();
    }
    if(getAnnualEntitlement())
    {
        ret["annual_entitlement"]=getValueOfAnnualEntitlement();
    }
    else
    {
        ret["annual_entitlement"]=Json::Value();
    }
    if(getRemainingLeave())
    {
        ret["remaining_leave"]=getValueOfRemainingLeave();
    }
    else
    {
        ret["remaining_leave"]=Json::Value();
    }
    return ret;
}

std::string LeaveAllowance::toString() const
{
    return toJson().toStyledString();
}

Json::Value LeaveAllowance::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getStaffId())
            {
                ret[pMasqueradingVector[1]]=getValueOfStaffId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getAnnualEntitlement())
            {
                ret[pMasqueradingVector[2]]=getValueOfAnnualEntitlement();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getRemainingLeave())
            {
                ret[pMasqueradingVector[3]]=getValueOfRemainingLeave();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getStaffId())
    {
        ret["staff_id"]=getValueOfStaffId();
    }
    else
    {
        ret["staff_id"]=Json::Value();
    }
    if(getAnnualEntitlement())
    {
        ret["annual_entitlement"]=getValueOfAnnualEntitlement();
    }
    else
    {
        ret["annual_entitlement"]=Json::Value();
    }
    if(getRemainingLeave())
    {
        ret["remaining_leave"]=getValueOfRemainingLeave();
    }
    else
    {
        ret["remaining_leave"]=Json::Value();
    }
    return ret;
}

bool LeaveAllowance::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    else
    {
        err="The id column cannot be null";
        return false;
    }
    if(pJson.isMember("staff_id"))
    {
        if(!validJsonOfField(1, "staff_id", pJson["staff_id"], err, true))
            return false;
    }
    else
    {
        err="The staff_id column cannot be null";
        return false;
    }
    if(pJson.isMember("annual_entitlement"))
    {
        if(!validJsonOfField(2, "annual_entitlement", pJson["annual_entitlement"], err, true))
            return false;
    }
    else
    {
        err="The annual_entitlement column cannot be null";
        return false;
    }
    if(pJson.isMember("remaining_leave"))
    {
        if(!validJsonOfField(3, "remaining_leave", pJson["remaining_leave"], err, true))
            return false;
    }
    else
    {
        err="The remaining_leave column cannot be null";
        return false;
    }
    return true;
}
bool LeaveAllowance::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool LeaveAllowance::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("staff_id"))
    {
        if(!validJsonOfField(1, "staff_id", pJson["staff_id"], err, false))
            return false;
    }
    if(pJson.isMember("annual_entitlement"))
    {
        if(!validJsonOfField(2, "annual_entitlement", pJson["annual_entitlement"], err, false))
            return false;
    }
    if(pJson.isMember("remaining_leave"))
    {
        if(!validJsonOfField(3, "remaining_leave", pJson["remaining_leave"], err, false))
            return false;
    }
    return true;
}
bool LeaveAllowance::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool LeaveAllowance::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
StaffMember LeaveAllowance::getStaffMember(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from staff_member where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *staffId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return StaffMember(r[0]);
}

void LeaveAllowance::getStaffMember(const DbClientPtr &clientPtr,
                                    const std::function<void(StaffMember)> &rcb,
                                    const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from staff_member where id = $1";
    *clientPtr << sql
               << *staffId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(StaffMember(r[0]));
                    }
               }
               >> ecb;
}
