/**
 *
 *  StaffMember.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */


#include "infrastructure/persistence/models/StaffMember.hpp"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::LeaveBooking;

const std::string StaffMember::Cols::_id = "\"id\"";
const std::string StaffMember::Cols::_first_name = "\"first_name\"";
const std::string StaffMember::Cols::_surname = "\"surname\"";
const std::string StaffMember::Cols::_house_name_number = "\"house_name_number\"";
const std::string StaffMember::Cols::_street = "\"street\"";
const std::string StaffMember::Cols::_town = "\"town\"";
const std::string StaffMember::Cols::_postcode = "\"postcode\"";
const std::string StaffMember::Cols::_role = "\"role\"";
const std::string StaffMember::Cols::_employment_status = "\"employment_status\"";
const std::string StaffMember::Cols::_manager_id = "\"manager_id\"";
const std::string StaffMember::primaryKeyName = "id";
const bool StaffMember::hasPrimaryKey = true;
const std::string StaffMember::tableName = "\"staff_member\"";

const std::vector<typename StaffMember::MetaData> StaffMember::metaData_={
{"id","std::string","text",0,0,1,1},
{"first_name","std::string","text",0,0,0,1},
{"surname","std::string","text",0,0,0,1},
{"house_name_number","std::string","text",0,0,0,0},
{"street","std::string","text",0,0,0,0},
{"town","std::string","text",0,0,0,0},
{"postcode","std::string","text",0,0,0,0},
{"role","std::string","text",0,0,0,1},
{"employment_status","std::string","text",0,0,0,1},
{"manager_id","std::string","text",0,0,0,0}
};
const std::string &StaffMember::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
StaffMember::StaffMember(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["first_name"].isNull())
        {
            firstName_=std::make_shared<std::string>(r["first_name"].as<std::string>());
        }
        if(!r["surname"].isNull())
        {
            surname_=std::make_shared<std::string>(r["surname"].as<std::string>());
        }
        if(!r["house_name_number"].isNull())
        {
            houseNameNumber_=std::make_shared<std::string>(r["house_name_number"].as<std::string>());
        }
        if(!r["street"].isNull())
        {
            street_=std::make_shared<std::string>(r["street"].as<std::string>());
        }
        if(!r["town"].isNull())
        {
            town_=std::make_shared<std::string>(r["town"].as<std::string>());
        }
        if(!r["postcode"].isNull())
        {
            postcode_=std::make_shared<std::string>(r["postcode"].as<std::string>());
        }
        if(!r["role"].isNull())
        {
            role_=std::make_shared<std::string>(r["role"].as<std::string>());
        }
        if(!r["employment_status"].isNull())
        {
            employmentStatus_=std::make_shared<std::string>(r["employment_status"].as<std::string>());
        }
        if(!r["manager_id"].isNull())
        {
            managerId_=std::make_shared<std::string>(r["manager_id"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 10 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            firstName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            surname_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            houseNameNumber_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            street_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            town_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            postcode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            role_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            employmentStatus_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            managerId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

StaffMember::StaffMember(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            firstName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            surname_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            houseNameNumber_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            street_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            town_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            postcode_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            role_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            employmentStatus_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            managerId_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
}

StaffMember::StaffMember(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("first_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["first_name"].isNull())
        {
            firstName_=std::make_shared<std::string>(pJson["first_name"].asString());
        }
    }
    if(pJson.isMember("surname"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["surname"].isNull())
        {
            surname_=std::make_shared<std::string>(pJson["surname"].asString());
        }
    }
    if(pJson.isMember("house_name_number"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["house_name_number"].isNull())
        {
            houseNameNumber_=std::make_shared<std::string>(pJson["house_name_number"].asString());
        }
    }
    if(pJson.isMember("street"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["street"].isNull())
        {
            street_=std::make_shared<std::string>(pJson["street"].asString());
        }
    }
    if(pJson.isMember("town"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["town"].isNull())
        {
            town_=std::make_shared<std::string>(pJson["town"].asString());
        }
    }
    if(pJson.isMember("postcode"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["postcode"].isNull())
        {
            postcode_=std::make_shared<std::string>(pJson["postcode"].asString());
        }
    }
    if(pJson.isMember("role"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["role"].isNull())
        {
            role_=std::make_shared<std::string>(pJson["role"].asString());
        }
    }
    if(pJson.isMember("employment_status"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["employment_status"].isNull())
        {
            employmentStatus_=std::make_shared<std::string>(pJson["employment_status"].asString());
        }
    }
    if(pJson.isMember("manager_id"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["manager_id"].isNull())
        {
            managerId_=std::make_shared<std::string>(pJson["manager_id"].asString());
        }
    }
}

void StaffMember::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            firstName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            surname_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            houseNameNumber_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            street_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            town_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            postcode_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            role_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            employmentStatus_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            managerId_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
}

void StaffMember::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("first_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["first_name"].isNull())
        {
            firstName_=std::make_shared<std::string>(pJson["first_name"].asString());
        }
    }
    if(pJson.isMember("surname"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["surname"].isNull())
        {
            surname_=std::make_shared<std::string>(pJson["surname"].asString());
        }
    }
    if(pJson.isMember("house_name_number"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["house_name_number"].isNull())
        {
            houseNameNumber_=std::make_shared<std::string>(pJson["house_name_number"].asString());
        }
    }
    if(pJson.isMember("street"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["street"].isNull())
        {
            street_=std::make_shared<std::string>(pJson["street"].asString());
        }
    }
    if(pJson.isMember("town"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["town"].isNull())
        {
            town_=std::make_shared<std::string>(pJson["town"].asString());
        }
    }
    if(pJson.isMember("postcode"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["postcode"].isNull())
        {
            postcode_=std::make_shared<std::string>(pJson["postcode"].asString());
        }
    }
    if(pJson.isMember("role"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["role"].isNull())
        {
            role_=std::make_shared<std::string>(pJson["role"].asString());
        }
    }
    if(pJson.isMember("employment_status"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["employment_status"].isNull())
        {
            employmentStatus_=std::make_shared<std::string>(pJson["employment_status"].asString());
        }
    }
    if(pJson.isMember("manager_id"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["manager_id"].isNull())
        {
            managerId_=std::make_shared<std::string>(pJson["manager_id"].asString());
        }
    }
}

const std::string &StaffMember::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &StaffMember::getId() const noexcept
{
    return id_;
}
void StaffMember::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void StaffMember::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename StaffMember::PrimaryKeyType & StaffMember::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &StaffMember::getValueOfFirstName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(firstName_)
        return *firstName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &StaffMember::getFirstName() const noexcept
{
    return firstName_;
}
void StaffMember::setFirstName(const std::string &pFirstName) noexcept
{
    firstName_ = std::make_shared<std::string>(pFirstName);
    dirtyFlag_[1] = true;
}
void StaffMember::setFirstName(std::string &&pFirstName) noexcept
{
    firstName_ = std::make_shared<std::string>(std::move(pFirstName));
    dirtyFlag_[1] = true;
}

const std::string &StaffMember::getValueOfSurname() const noexcept
{
    static const std::string defaultValue = std::string();
    if(surname_)
        return *surname_;
    return defaultValue;
}
const std::shared_ptr<std::string> &StaffMember::getSurname() const noexcept
{
    return surname_;
}
void StaffMember::setSurname(const std::string &pSurname) noexcept
{
    surname_ = std::make_shared<std::string>(pSurname);
    dirtyFlag_[2] = true;
}
void StaffMember::setSurname(std::string &&pSurname) noexcept
{
    surname_ = std::make_shared<std::string>(std::move(pSurname));
    dirtyFlag_[2] = true;
}

const std::string &StaffMember::getValueOfHouseNameNumber() const noexcept
{
    static const std::string defaultValue = std::string();
    if(houseNameNumber_)
        return *houseNameNumber_;
    return defaultValue;
}
const std::shared_ptr<std::string> &StaffMember::getHouseNameNumber() const noexcept
{
    return houseNameNumber_;
}
void StaffMember::setHouseNameNumber(const std::string &pHouseNameNumber) noexcept
{
    houseNameNumber_ = std::make_shared<std::string>(pHouseNameNumber);
    dirtyFlag_[3] = true;
}
void StaffMember::setHouseNameNumber(std::string &&pHouseNameNumber) noexcept
{
    houseNameNumber_ = std::make_shared<std::string>(std::move(pHouseNameNumber));
    dirtyFlag_[3] = true;
}
void StaffMember::setHouseNameNumberToNull() noexcept
{
    houseNameNumber_.reset();
    dirtyFlag_[3] = true;
}

const std::string &StaffMember::getValueOfStreet() const noexcept
{
    static const std::string defaultValue = std::string();
    if(street_)
        return *street_;
    return defaultValue;
}
const std::shared_ptr<std::string> &StaffMember::getStreet() const noexcept
{
    return street_;
}
void StaffMember::setStreet(const std::string &pStreet) noexcept
{
    street_ = std::make_shared<std::string>(pStreet);
    dirtyFlag_[4] = true;
}
void StaffMember::setStreet(std::string &&pStreet) noexcept
{
    street_ = std::make_shared<std::string>(std::move(pStreet));
    dirtyFlag_[4] = true;
}
void StaffMember::setStreetToNull() noexcept
{
    street_.reset();
    dirtyFlag_[4] = true;
}

const std::string &StaffMember::getValueOfTown() const noexcept
{
    static const std::string defaultValue = std::string();
    if(town_)
        return *town_;
    return defaultValue;
}
const std::shared_ptr<std::string> &StaffMember::getTown() const noexcept
{
    return town_;
}
void StaffMember::setTown(const std::string &pTown) noexcept
{
    town_ = std::make_shared<std::string>(pTown);
    dirtyFlag_[5] = true;
}
void StaffMember::setTown(std::string &&pTown) noexcept
{
    town_ = std::make_shared<std::string>(std::move(pTown));
    dirtyFlag_[5] = true;
}
void StaffMember::setTownToNull() noexcept
{
    town_.reset();
    dirtyFlag_[5] = true;
}

const std::string &StaffMember::getValueOfPostcode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(postcode_)
        return *postcode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &StaffMember::getPostcode() const noexcept
{
    return postcode_;
}
void StaffMember::setPostcode(const std::string &pPostcode) noexcept
{
    postcode_ = std::make_shared<std::string>(pPostcode);
    dirtyFlag_[6] = true;
}
void StaffMember::setPostcode(std::string &&pPostcode) noexcept
{
    postcode_ = std::make_shared<std::string>(std::move(pPostcode));
    dirtyFlag_[6] = true;
}
void StaffMember::setPostcodeToNull() noexcept
{
    postcode_.reset();
    dirtyFlag_[6] = true;
}

const std::string &StaffMember::getValueOfRole() const noexcept
{
    static const std::string defaultValue = std::string();
    if(role_)
        return *role_;
    return defaultValue;
}
const std::shared_ptr<std::string> &StaffMember::getRole() const noexcept
{
    return role_;
}
void StaffMember::setRole(const std::string &pRole) noexcept
{
    role_ = std::make_shared<std::string>(pRole);
    dirtyFlag_[7] = true;
}
void StaffMember::setRole(std::string &&pRole) noexcept
{
    role_ = std::make_shared<std::string>(std::move(pRole));
    dirtyFlag_[7] = true;
}

const std::string &StaffMember::getValueOfEmploymentStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(employmentStatus_)
        return *employmentStatus_;
    return defaultValue;
}
const std::shared_ptr<std::string> &StaffMember::getEmploymentStatus() const noexcept
{
    return employmentStatus_;
}
void StaffMember::setEmploymentStatus(const std::string &pEmploymentStatus) noexcept
{
    employmentStatus_ = std::make_shared<std::string>(pEmploymentStatus);
    dirtyFlag_[8] = true;
}
void StaffMember::setEmploymentStatus(std::string &&pEmploymentStatus) noexcept
{
    employmentStatus_ = std::make_shared<std::string>(std::move(pEmploymentStatus));
    dirtyFlag_[8] = true;
}

const std::string &StaffMember::getValueOfManagerId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(managerId_)
        return *managerId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &StaffMember::getManagerId() const noexcept
{
    return managerId_;
}
void StaffMember::setManagerId(const std::string &pManagerId) noexcept
{
    managerId_ = std::make_shared<std::string>(pManagerId);
    dirtyFlag_[9] = true;
}
void StaffMember::setManagerId(std::string &&pManagerId) noexcept
{
    managerId_ = std::make_shared<std::string>(std::move(pManagerId));
    dirtyFlag_[9] = true;
}
void StaffMember::setManagerIdToNull() noexcept
{
    managerId_.reset();
    dirtyFlag_[9] = true;
}

void StaffMember::updateId(const uint64_t id)
{
}

const std::vector<std::string> &StaffMember::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "first_name",
        "surname",
        "house_name_number",
        "street",
        "town",
        "postcode",
        "role",
        "employment_status",
        "manager_id"
    };
    return inCols;
}

void StaffMember::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getFirstName())
        {
            binder << getValueOfFirstName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSurname())
        {
            binder << getValueOfSurname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getHouseNameNumber())
        {
            binder << getValueOfHouseNameNumber();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStreet())
        {
            binder << getValueOfStreet();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTown())
        {
            binder << getValueOfTown();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPostcode())
        {
            binder << getValueOfPostcode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getRole())
        {
            binder << getValueOfRole();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getEmploymentStatus())
        {
            binder << getValueOfEmploymentStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getManagerId())
        {
            binder << getValueOfManagerId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> StaffMember::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    return ret;
}

void StaffMember::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getFirstName())
        {
            binder << getValueOfFirstName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSurname())
        {
            binder << getValueOfSurname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getHouseNameNumber())
        {
            binder << getValueOfHouseNameNumber();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStreet())
        {
            binder << getValueOfStreet();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTown())
        {
            binder << getValueOfTown();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPostcode())
        {
            binder << getValueOfPostcode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getRole())
        {
            binder << getValueOfRole();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getEmploymentStatus())
        {
            binder << getValueOfEmploymentStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getManagerId())
        {
            binder << getValueOfManagerId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value StaffMember::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getFirstName())
    {
        ret["first_name"]=getValueOfFirstName();
    }
    else
    {
        ret["first_name"]=Json::Value();
    }
    if(getSurname())
    {
        ret["surname"]=getValueOfSurname();
    }
    else
    {
        ret["surname"]=Json::Value();
    }
    if(getHouseNameNumber())
    {
        ret["house_name_number"]=getValueOfHouseNameNumber();
    }
    else
    {
        ret["house_name_number"]=Json::Value();
    }
    if(getStreet())
    {
        ret["street"]=getValueOfStreet();
    }
    else
    {
        ret["street"]=Json::Value();
    }
    if(getTown())
    {
        ret["town"]=getValueOfTown();
    }
    else
    {
        ret["town"]=Json::Value();
    }
    if(getPostcode())
    {
        ret["postcode"]=getValueOfPostcode();
    }
    else
    {
        ret["postcode"]=Json::Value();
    }
    if(getRole())
    {
        ret["role"]=getValueOfRole();
    }
    else
    {
        ret["role"]=Json::Value();
    }
    if(getEmploymentStatus())
    {
        ret["employment_status"]=getValueOfEmploymentStatus();
    }
    else
    {
        ret["employment_status"]=Json::Value();
    }
    if(getManagerId())
    {
        ret["manager_id"]=getValueOfManagerId();
    }
    else
    {
        ret["manager_id"]=Json::Value();
    }
    return ret;
}

std::string StaffMember::toString() const
{
    return toJson().toStyledString();
}

Json::Value StaffMember::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 10)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getFirstName())
            {
                ret[pMasqueradingVector[1]]=getValueOfFirstName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getSurname())
            {
                ret[pMasqueradingVector[2]]=getValueOfSurname();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getHouseNameNumber())
            {
                ret[pMasqueradingVector[3]]=getValueOfHouseNameNumber();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getStreet())
            {
                ret[pMasqueradingVector[4]]=getValueOfStreet();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getTown())
            {
                ret[pMasqueradingVector[5]]=getValueOfTown();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getPostcode())
            {
                ret[pMasqueradingVector[6]]=getValueOfPostcode();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getRole())
            {
                ret[pMasqueradingVector[7]]=getValueOfRole();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getEmploymentStatus())
            {
                ret[pMasqueradingVector[8]]=getValueOfEmploymentStatus();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getManagerId())
            {
                ret[pMasqueradingVector[9]]=getValueOfManagerId();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getFirstName())
    {
        ret["first_name"]=getValueOfFirstName();
    }
    else
    {
        ret["first_name"]=Json::Value();
    }
    if(getSurname())
    {
        ret["surname"]=getValueOfSurname();
    }
    else
    {
        ret["surname"]=Json::Value();
    }
    if(getHouseNameNumber())
    {
        ret["house_name_number"]=getValueOfHouseNameNumber();
    }
    else
    {
        ret["house_name_number"]=Json::Value();
    }
    if(getStreet())
    {
        ret["street"]=getValueOfStreet();
    }
    else
    {
        ret["street"]=Json::Value();
    }
    if(getTown())
    {
        ret["town"]=getValueOfTown();
    }
    else
    {
        ret["town"]=Json::Value();
    }
    if(getPostcode())
    {
        ret["postcode"]=getValueOfPostcode();
    }
    else
    {
        ret["postcode"]=Json::Value();
    }
    if(getRole())
    {
        ret["role"]=getValueOfRole();
    }
    else
    {
        ret["role"]=Json::Value();
    }
    if(getEmploymentStatus())
    {
        ret["employment_status"]=getValueOfEmploymentStatus();
    }
    else
    {
        ret["employment_status"]=Json::Value();
    }
    if(getManagerId())
    {
        ret["manager_id"]=getValueOfManagerId();
    }
    else
    {
        ret["manager_id"]=Json::Value();
    }
    return ret;
}

bool StaffMember::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    else
    {
        err="The id column cannot be null";
        return false;
    }
    if(pJson.isMember("first_name"))
    {
        if(!validJsonOfField(1, "first_name", pJson["first_name"], err, true))
            return false;
    }
    else
    {
        err="The first_name column cannot be null";
        return false;
    }
    if(pJson.isMember("surname"))
    {
        if(!validJsonOfField(2, "surname", pJson["surname"], err, true))
            return false;
    }
    else
    {
        err="The surname column cannot be null";
        return false;
    }
    if(pJson.isMember("house_name_number"))
    {
        if(!validJsonOfField(3, "house_name_number", pJson["house_name_number"], err, true))
            return false;
    }
    if(pJson.isMember("street"))
    {
        if(!validJsonOfField(4, "street", pJson["street"], err, true))
            return false;
    }
    if(pJson.isMember("town"))
    {
        if(!validJsonOfField(5, "town", pJson["town"], err, true))
            return false;
    }
    if(pJson.isMember("postcode"))
    {
        if(!validJsonOfField(6, "postcode", pJson["postcode"], err, true))
            return false;
    }
    if(pJson.isMember("role"))
    {
        if(!validJsonOfField(7, "role", pJson["role"], err, true))
            return false;
    }
    else
    {
        err="The role column cannot be null";
        return false;
    }
    if(pJson.isMember("employment_status"))
    {
        if(!validJsonOfField(8, "employment_status", pJson["employment_status"], err, true))
            return false;
    }
    else
    {
        err="The employment_status column cannot be null";
        return false;
    }
    if(pJson.isMember("manager_id"))
    {
        if(!validJsonOfField(9, "manager_id", pJson["manager_id"], err, true))
            return false;
    }
    return true;
}
bool StaffMember::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool StaffMember::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("first_name"))
    {
        if(!validJsonOfField(1, "first_name", pJson["first_name"], err, false))
            return false;
    }
    if(pJson.isMember("surname"))
    {
        if(!validJsonOfField(2, "surname", pJson["surname"], err, false))
            return false;
    }
    if(pJson.isMember("house_name_number"))
    {
        if(!validJsonOfField(3, "house_name_number", pJson["house_name_number"], err, false))
            return false;
    }
    if(pJson.isMember("street"))
    {
        if(!validJsonOfField(4, "street", pJson["street"], err, false))
            return false;
    }
    if(pJson.isMember("town"))
    {
        if(!validJsonOfField(5, "town", pJson["town"], err, false))
            return false;
    }
    if(pJson.isMember("postcode"))
    {
        if(!validJsonOfField(6, "postcode", pJson["postcode"], err, false))
            return false;
    }
    if(pJson.isMember("role"))
    {
        if(!validJsonOfField(7, "role", pJson["role"], err, false))
            return false;
    }
    if(pJson.isMember("employment_status"))
    {
        if(!validJsonOfField(8, "employment_status", pJson["employment_status"], err, false))
            return false;
    }
    if(pJson.isMember("manager_id"))
    {
        if(!validJsonOfField(9, "manager_id", pJson["manager_id"], err, false))
            return false;
    }
    return true;
}
bool StaffMember::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool StaffMember::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
StaffMember StaffMember::getStaffMember(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from staff_member where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *managerId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return StaffMember(r[0]);
}

void StaffMember::getStaffMember(const DbClientPtr &clientPtr,
                                 const std::function<void(StaffMember)> &rcb,
                                 const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from staff_member where id = $1";
    *clientPtr << sql
               << *managerId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(StaffMember(r[0]));
                    }
               }
               >> ecb;
}
